# Generated by Django 3.2.5 on 2021-09-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210908_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-pub_date',)},
        ),
    ]
